### ISSUE TITLE
如何扩展Page的生命周期函数onNavigate, 又如何触发。

### ISSUE THREAD

**Issue by Dragon-Rider** [ysbcc/miniapp#2]
您好

想请问下，您是如何扩展page的生命周期函数onNavite的呢？

又是如何触发的呢？将下个页面onNavite的触发条件写在上一个页面的this.$route里面吗？

全局的缓存方法，$put()和$take()，数据结构里数据有一个全局的大objeck？‘play-detail’作为一个key存储了吗？

期望能得到您的解答，如果有源码能参考下就更好了，thx~~

**Comment by ysbcc** [comment]
hello，
我们封装了一个开源的开发框架，可以在这里查看到源码。https://github.com/tvfe/wxpage

**Comment by Dragon-Rider** [comment]
感谢分享，我去参考下哈~
